-- Import produktów sklepu z Katalogu konsol (console_catalog) — jednorazowy, 06.10.2026.
-- Uruchom PO aktualnym supabase/shop.sql (klasa "zadowalający" + ukrywanie wariantów z ceną 0).
-- Wygenerowane z katalogu w stanie na dzień importu: 13 modeli (rodzina konsoli = model), wariant = dysk · kolor · pady × klasa.
-- Klasy: A = bardzo dobry, B = dobry, C = zadowalający. SKU = SKU z katalogu (z końcówką -0M/-1M/-2M).
-- Ceny 0 i stan 0: warianty są niewidoczne w sklepie, dopóki nie dostaną ceny (ERP → Recoo Sklep → Produkty).
-- Nowe modele startują jako szkice (published = false). Bezpieczne do ponownego uruchomienia: nic nie nadpisuje cen, stanów ani opisów.
begin;

insert into shop_models (slug, name, brand, category_slug, option_label, color, keywords, published, sort)
values
  ('playstation-5-slim-digital', 'PlayStation 5 Slim Digital Edition', 'Sony', 'konsole', 'Dysk · Kolor · Pady', '#E1F0FE', 'ps5 slim digital bez napędu', false, 20),
  ('playstation-5-pro', 'PlayStation 5 Pro', 'Sony', 'konsole', 'Dysk · Kolor · Pady', '#E1F0FE', 'ps5 pro', false, 22),
  ('playstation-5-digital', 'PlayStation 5 Digital Edition', 'Sony', 'konsole', 'Dysk · Kolor · Pady', '#E1F0FE', 'ps5 digital bez napędu pierwsza generacja', false, 23),
  ('playstation-4-slim', 'PlayStation 4 Slim', 'Sony', 'konsole', 'Dysk · Kolor · Pady', '#E1F0FE', 'ps4 slim playstation 4', false, 25),
  ('playstation-4', 'PlayStation 4', 'Sony', 'konsole', 'Dysk · Kolor · Pady', '#E1F0FE', 'ps4 playstation 4 fat', false, 27),
  ('xbox-one-x', 'Xbox One X', 'Microsoft', 'konsole', 'Dysk · Kolor · Pady', '#D9F8EF', 'xbox one x xox', false, 30),
  ('xbox-one-s', 'Xbox One S', 'Microsoft', 'konsole', 'Dysk · Kolor · Pady', '#D9F8EF', 'xbox one s xos', false, 31),
  ('xbox-one', 'Xbox One', 'Microsoft', 'konsole', 'Dysk · Kolor · Pady', '#D9F8EF', 'xbox one', false, 32)
on conflict (slug) do nothing;

-- Modele, które już były w sklepie (dane przykładowe): opcja w trzech wymiarach, przykładowe warianty wyłączone (nie usunięte).
update shop_models set option_label = 'Dysk · Kolor · Pady' where slug in ('playstation-5-slim', 'playstation-5', 'playstation-4-pro', 'xbox-series-x', 'xbox-series-s');
-- Przykładowe warianty = te z opcją w starym, jednowymiarowym kształcie (bez ' · ').
update shop_variants set active = false where active and option_value not like '% · %'
  and model_id in (select id from shop_models where slug in ('playstation-5-slim', 'playstation-5', 'playstation-4-pro', 'xbox-series-x', 'xbox-series-s'));

insert into shop_variants (model_id, sku, option_value, grade, price, stock, active, sort)
select m.id, v.sku, v.option_value, v.grade, 0, 0, true, v.sort from (values
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 1),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 2),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 4),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 5),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 7),
  ('playstation-5-slim-digital', 'PS5SD-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 8),
  ('playstation-5-slim', 'PS5S-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('playstation-5-slim', 'PS5S-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 1),
  ('playstation-5-slim', 'PS5S-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 2),
  ('playstation-5-slim', 'PS5S-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('playstation-5-slim', 'PS5S-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 4),
  ('playstation-5-slim', 'PS5S-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 5),
  ('playstation-5-slim', 'PS5S-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('playstation-5-slim', 'PS5S-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 7),
  ('playstation-5-slim', 'PS5S-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 8),
  ('playstation-5-pro', 'PS5P-2TB-WE-A-0M', '2 TB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('playstation-5-pro', 'PS5P-2TB-WE-B-0M', '2 TB · Biały · Bez padów', 'dobry', 1),
  ('playstation-5-pro', 'PS5P-2TB-WE-C-0M', '2 TB · Biały · Bez padów', 'zadowalajacy', 2),
  ('playstation-5-pro', 'PS5P-2TB-WE-A-1M', '2 TB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('playstation-5-pro', 'PS5P-2TB-WE-B-1M', '2 TB · Biały · 1 pad', 'dobry', 4),
  ('playstation-5-pro', 'PS5P-2TB-WE-C-1M', '2 TB · Biały · 1 pad', 'zadowalajacy', 5),
  ('playstation-5-pro', 'PS5P-2TB-WE-A-2M', '2 TB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('playstation-5-pro', 'PS5P-2TB-WE-B-2M', '2 TB · Biały · 2 pady', 'dobry', 7),
  ('playstation-5-pro', 'PS5P-2TB-WE-C-2M', '2 TB · Biały · 2 pady', 'zadowalajacy', 8),
  ('playstation-5-digital', 'PS5D-825-WE-A-0M', '825 GB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('playstation-5-digital', 'PS5D-825-WE-B-0M', '825 GB · Biały · Bez padów', 'dobry', 1),
  ('playstation-5-digital', 'PS5D-825-WE-C-0M', '825 GB · Biały · Bez padów', 'zadowalajacy', 2),
  ('playstation-5-digital', 'PS5D-825-WE-A-1M', '825 GB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('playstation-5-digital', 'PS5D-825-WE-B-1M', '825 GB · Biały · 1 pad', 'dobry', 4),
  ('playstation-5-digital', 'PS5D-825-WE-C-1M', '825 GB · Biały · 1 pad', 'zadowalajacy', 5),
  ('playstation-5-digital', 'PS5D-825-WE-A-2M', '825 GB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('playstation-5-digital', 'PS5D-825-WE-B-2M', '825 GB · Biały · 2 pady', 'dobry', 7),
  ('playstation-5-digital', 'PS5D-825-WE-C-2M', '825 GB · Biały · 2 pady', 'zadowalajacy', 8),
  ('playstation-5', 'PS5-825-WE-A-0M', '825 GB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('playstation-5', 'PS5-825-WE-B-0M', '825 GB · Biały · Bez padów', 'dobry', 1),
  ('playstation-5', 'PS5-825-WE-C-0M', '825 GB · Biały · Bez padów', 'zadowalajacy', 2),
  ('playstation-5', 'PS5-825-WE-A-1M', '825 GB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('playstation-5', 'PS5-825-WE-B-1M', '825 GB · Biały · 1 pad', 'dobry', 4),
  ('playstation-5', 'PS5-825-WE-C-1M', '825 GB · Biały · 1 pad', 'zadowalajacy', 5),
  ('playstation-5', 'PS5-825-WE-A-2M', '825 GB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('playstation-5', 'PS5-825-WE-B-2M', '825 GB · Biały · 2 pady', 'dobry', 7),
  ('playstation-5', 'PS5-825-WE-C-2M', '825 GB · Biały · 2 pady', 'zadowalajacy', 8),
  ('playstation-4-slim', 'PS4S-500-BK-A-0M', '500 GB · Czarny · Bez padów', 'bardzo-dobry', 0),
  ('playstation-4-slim', 'PS4S-500-BK-B-0M', '500 GB · Czarny · Bez padów', 'dobry', 1),
  ('playstation-4-slim', 'PS4S-500-BK-C-0M', '500 GB · Czarny · Bez padów', 'zadowalajacy', 2),
  ('playstation-4-slim', 'PS4S-500-BK-A-1M', '500 GB · Czarny · 1 pad', 'bardzo-dobry', 3),
  ('playstation-4-slim', 'PS4S-500-BK-B-1M', '500 GB · Czarny · 1 pad', 'dobry', 4),
  ('playstation-4-slim', 'PS4S-500-BK-C-1M', '500 GB · Czarny · 1 pad', 'zadowalajacy', 5),
  ('playstation-4-slim', 'PS4S-500-BK-A-2M', '500 GB · Czarny · 2 pady', 'bardzo-dobry', 6),
  ('playstation-4-slim', 'PS4S-500-BK-B-2M', '500 GB · Czarny · 2 pady', 'dobry', 7),
  ('playstation-4-slim', 'PS4S-500-BK-C-2M', '500 GB · Czarny · 2 pady', 'zadowalajacy', 8),
  ('playstation-4-slim', 'PS4S-500-WE-A-0M', '500 GB · Biały · Bez padów', 'bardzo-dobry', 9),
  ('playstation-4-slim', 'PS4S-500-WE-B-0M', '500 GB · Biały · Bez padów', 'dobry', 10),
  ('playstation-4-slim', 'PS4S-500-WE-C-0M', '500 GB · Biały · Bez padów', 'zadowalajacy', 11),
  ('playstation-4-slim', 'PS4S-500-WE-A-1M', '500 GB · Biały · 1 pad', 'bardzo-dobry', 12),
  ('playstation-4-slim', 'PS4S-500-WE-B-1M', '500 GB · Biały · 1 pad', 'dobry', 13),
  ('playstation-4-slim', 'PS4S-500-WE-C-1M', '500 GB · Biały · 1 pad', 'zadowalajacy', 14),
  ('playstation-4-slim', 'PS4S-500-WE-A-2M', '500 GB · Biały · 2 pady', 'bardzo-dobry', 15),
  ('playstation-4-slim', 'PS4S-500-WE-B-2M', '500 GB · Biały · 2 pady', 'dobry', 16),
  ('playstation-4-slim', 'PS4S-500-WE-C-2M', '500 GB · Biały · 2 pady', 'zadowalajacy', 17),
  ('playstation-4-slim', 'PS4S-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 18),
  ('playstation-4-slim', 'PS4S-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 19),
  ('playstation-4-slim', 'PS4S-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 20),
  ('playstation-4-slim', 'PS4S-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 21),
  ('playstation-4-slim', 'PS4S-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 22),
  ('playstation-4-slim', 'PS4S-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 23),
  ('playstation-4-slim', 'PS4S-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 24),
  ('playstation-4-slim', 'PS4S-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 25),
  ('playstation-4-slim', 'PS4S-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 26),
  ('playstation-4-slim', 'PS4S-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 27),
  ('playstation-4-slim', 'PS4S-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 28),
  ('playstation-4-slim', 'PS4S-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 29),
  ('playstation-4-slim', 'PS4S-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 30),
  ('playstation-4-slim', 'PS4S-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 31),
  ('playstation-4-slim', 'PS4S-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 32),
  ('playstation-4-slim', 'PS4S-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 33),
  ('playstation-4-slim', 'PS4S-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 34),
  ('playstation-4-slim', 'PS4S-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 35),
  ('playstation-4-pro', 'PS4P-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 0),
  ('playstation-4-pro', 'PS4P-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 1),
  ('playstation-4-pro', 'PS4P-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 2),
  ('playstation-4-pro', 'PS4P-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 3),
  ('playstation-4-pro', 'PS4P-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 4),
  ('playstation-4-pro', 'PS4P-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 5),
  ('playstation-4-pro', 'PS4P-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 6),
  ('playstation-4-pro', 'PS4P-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 7),
  ('playstation-4-pro', 'PS4P-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 8),
  ('playstation-4-pro', 'PS4P-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 9),
  ('playstation-4-pro', 'PS4P-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 10),
  ('playstation-4-pro', 'PS4P-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 11),
  ('playstation-4-pro', 'PS4P-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 12),
  ('playstation-4-pro', 'PS4P-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 13),
  ('playstation-4-pro', 'PS4P-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 14),
  ('playstation-4-pro', 'PS4P-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 15),
  ('playstation-4-pro', 'PS4P-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 16),
  ('playstation-4-pro', 'PS4P-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 17),
  ('playstation-4', 'PS4-500-BK-A-0M', '500 GB · Czarny · Bez padów', 'bardzo-dobry', 0),
  ('playstation-4', 'PS4-500-BK-B-0M', '500 GB · Czarny · Bez padów', 'dobry', 1),
  ('playstation-4', 'PS4-500-BK-C-0M', '500 GB · Czarny · Bez padów', 'zadowalajacy', 2),
  ('playstation-4', 'PS4-500-BK-A-1M', '500 GB · Czarny · 1 pad', 'bardzo-dobry', 3),
  ('playstation-4', 'PS4-500-BK-B-1M', '500 GB · Czarny · 1 pad', 'dobry', 4),
  ('playstation-4', 'PS4-500-BK-C-1M', '500 GB · Czarny · 1 pad', 'zadowalajacy', 5),
  ('playstation-4', 'PS4-500-BK-A-2M', '500 GB · Czarny · 2 pady', 'bardzo-dobry', 6),
  ('playstation-4', 'PS4-500-BK-B-2M', '500 GB · Czarny · 2 pady', 'dobry', 7),
  ('playstation-4', 'PS4-500-BK-C-2M', '500 GB · Czarny · 2 pady', 'zadowalajacy', 8),
  ('playstation-4', 'PS4-500-WE-A-0M', '500 GB · Biały · Bez padów', 'bardzo-dobry', 9),
  ('playstation-4', 'PS4-500-WE-B-0M', '500 GB · Biały · Bez padów', 'dobry', 10),
  ('playstation-4', 'PS4-500-WE-C-0M', '500 GB · Biały · Bez padów', 'zadowalajacy', 11),
  ('playstation-4', 'PS4-500-WE-A-1M', '500 GB · Biały · 1 pad', 'bardzo-dobry', 12),
  ('playstation-4', 'PS4-500-WE-B-1M', '500 GB · Biały · 1 pad', 'dobry', 13),
  ('playstation-4', 'PS4-500-WE-C-1M', '500 GB · Biały · 1 pad', 'zadowalajacy', 14),
  ('playstation-4', 'PS4-500-WE-A-2M', '500 GB · Biały · 2 pady', 'bardzo-dobry', 15),
  ('playstation-4', 'PS4-500-WE-B-2M', '500 GB · Biały · 2 pady', 'dobry', 16),
  ('playstation-4', 'PS4-500-WE-C-2M', '500 GB · Biały · 2 pady', 'zadowalajacy', 17),
  ('playstation-4', 'PS4-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 18),
  ('playstation-4', 'PS4-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 19),
  ('playstation-4', 'PS4-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 20),
  ('playstation-4', 'PS4-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 21),
  ('playstation-4', 'PS4-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 22),
  ('playstation-4', 'PS4-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 23),
  ('playstation-4', 'PS4-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 24),
  ('playstation-4', 'PS4-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 25),
  ('playstation-4', 'PS4-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 26),
  ('playstation-4', 'PS4-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 27),
  ('playstation-4', 'PS4-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 28),
  ('playstation-4', 'PS4-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 29),
  ('playstation-4', 'PS4-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 30),
  ('playstation-4', 'PS4-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 31),
  ('playstation-4', 'PS4-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 32),
  ('playstation-4', 'PS4-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 33),
  ('playstation-4', 'PS4-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 34),
  ('playstation-4', 'PS4-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 35),
  ('xbox-series-x', 'XSX-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 0),
  ('xbox-series-x', 'XSX-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 1),
  ('xbox-series-x', 'XSX-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 2),
  ('xbox-series-x', 'XSX-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 3),
  ('xbox-series-x', 'XSX-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 4),
  ('xbox-series-x', 'XSX-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 5),
  ('xbox-series-x', 'XSX-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 6),
  ('xbox-series-x', 'XSX-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 7),
  ('xbox-series-x', 'XSX-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 8),
  ('xbox-series-s', 'XSS-512-WE-A-0M', '512 GB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('xbox-series-s', 'XSS-512-WE-B-0M', '512 GB · Biały · Bez padów', 'dobry', 1),
  ('xbox-series-s', 'XSS-512-WE-C-0M', '512 GB · Biały · Bez padów', 'zadowalajacy', 2),
  ('xbox-series-s', 'XSS-512-WE-A-1M', '512 GB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('xbox-series-s', 'XSS-512-WE-B-1M', '512 GB · Biały · 1 pad', 'dobry', 4),
  ('xbox-series-s', 'XSS-512-WE-C-1M', '512 GB · Biały · 1 pad', 'zadowalajacy', 5),
  ('xbox-series-s', 'XSS-512-WE-A-2M', '512 GB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('xbox-series-s', 'XSS-512-WE-B-2M', '512 GB · Biały · 2 pady', 'dobry', 7),
  ('xbox-series-s', 'XSS-512-WE-C-2M', '512 GB · Biały · 2 pady', 'zadowalajacy', 8),
  ('xbox-series-s', 'XSS-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 9),
  ('xbox-series-s', 'XSS-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 10),
  ('xbox-series-s', 'XSS-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 11),
  ('xbox-series-s', 'XSS-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 12),
  ('xbox-series-s', 'XSS-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 13),
  ('xbox-series-s', 'XSS-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 14),
  ('xbox-series-s', 'XSS-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 15),
  ('xbox-series-s', 'XSS-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 16),
  ('xbox-series-s', 'XSS-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 17),
  ('xbox-series-s', 'XSS-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 18),
  ('xbox-series-s', 'XSS-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 19),
  ('xbox-series-s', 'XSS-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 20),
  ('xbox-series-s', 'XSS-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 21),
  ('xbox-series-s', 'XSS-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 22),
  ('xbox-series-s', 'XSS-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 23),
  ('xbox-series-s', 'XSS-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 24),
  ('xbox-series-s', 'XSS-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 25),
  ('xbox-series-s', 'XSS-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 26),
  ('xbox-one-x', 'XOX-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 0),
  ('xbox-one-x', 'XOX-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 1),
  ('xbox-one-x', 'XOX-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 2),
  ('xbox-one-x', 'XOX-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 3),
  ('xbox-one-x', 'XOX-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 4),
  ('xbox-one-x', 'XOX-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 5),
  ('xbox-one-x', 'XOX-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 6),
  ('xbox-one-x', 'XOX-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 7),
  ('xbox-one-x', 'XOX-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 8),
  ('xbox-one-s', 'XOS-500-WE-A-0M', '500 GB · Biały · Bez padów', 'bardzo-dobry', 0),
  ('xbox-one-s', 'XOS-500-WE-B-0M', '500 GB · Biały · Bez padów', 'dobry', 1),
  ('xbox-one-s', 'XOS-500-WE-C-0M', '500 GB · Biały · Bez padów', 'zadowalajacy', 2),
  ('xbox-one-s', 'XOS-500-WE-A-1M', '500 GB · Biały · 1 pad', 'bardzo-dobry', 3),
  ('xbox-one-s', 'XOS-500-WE-B-1M', '500 GB · Biały · 1 pad', 'dobry', 4),
  ('xbox-one-s', 'XOS-500-WE-C-1M', '500 GB · Biały · 1 pad', 'zadowalajacy', 5),
  ('xbox-one-s', 'XOS-500-WE-A-2M', '500 GB · Biały · 2 pady', 'bardzo-dobry', 6),
  ('xbox-one-s', 'XOS-500-WE-B-2M', '500 GB · Biały · 2 pady', 'dobry', 7),
  ('xbox-one-s', 'XOS-500-WE-C-2M', '500 GB · Biały · 2 pady', 'zadowalajacy', 8),
  ('xbox-one-s', 'XOS-1TB-WE-A-0M', '1 TB · Biały · Bez padów', 'bardzo-dobry', 9),
  ('xbox-one-s', 'XOS-1TB-WE-B-0M', '1 TB · Biały · Bez padów', 'dobry', 10),
  ('xbox-one-s', 'XOS-1TB-WE-C-0M', '1 TB · Biały · Bez padów', 'zadowalajacy', 11),
  ('xbox-one-s', 'XOS-1TB-WE-A-1M', '1 TB · Biały · 1 pad', 'bardzo-dobry', 12),
  ('xbox-one-s', 'XOS-1TB-WE-B-1M', '1 TB · Biały · 1 pad', 'dobry', 13),
  ('xbox-one-s', 'XOS-1TB-WE-C-1M', '1 TB · Biały · 1 pad', 'zadowalajacy', 14),
  ('xbox-one-s', 'XOS-1TB-WE-A-2M', '1 TB · Biały · 2 pady', 'bardzo-dobry', 15),
  ('xbox-one-s', 'XOS-1TB-WE-B-2M', '1 TB · Biały · 2 pady', 'dobry', 16),
  ('xbox-one-s', 'XOS-1TB-WE-C-2M', '1 TB · Biały · 2 pady', 'zadowalajacy', 17),
  ('xbox-one-s', 'XOS-2TB-WE-A-0M', '2 TB · Biały · Bez padów', 'bardzo-dobry', 18),
  ('xbox-one-s', 'XOS-2TB-WE-B-0M', '2 TB · Biały · Bez padów', 'dobry', 19),
  ('xbox-one-s', 'XOS-2TB-WE-C-0M', '2 TB · Biały · Bez padów', 'zadowalajacy', 20),
  ('xbox-one-s', 'XOS-2TB-WE-A-1M', '2 TB · Biały · 1 pad', 'bardzo-dobry', 21),
  ('xbox-one-s', 'XOS-2TB-WE-B-1M', '2 TB · Biały · 1 pad', 'dobry', 22),
  ('xbox-one-s', 'XOS-2TB-WE-C-1M', '2 TB · Biały · 1 pad', 'zadowalajacy', 23),
  ('xbox-one-s', 'XOS-2TB-WE-A-2M', '2 TB · Biały · 2 pady', 'bardzo-dobry', 24),
  ('xbox-one-s', 'XOS-2TB-WE-B-2M', '2 TB · Biały · 2 pady', 'dobry', 25),
  ('xbox-one-s', 'XOS-2TB-WE-C-2M', '2 TB · Biały · 2 pady', 'zadowalajacy', 26),
  ('xbox-one', 'XO-500-BK-A-0M', '500 GB · Czarny · Bez padów', 'bardzo-dobry', 0),
  ('xbox-one', 'XO-500-BK-B-0M', '500 GB · Czarny · Bez padów', 'dobry', 1),
  ('xbox-one', 'XO-500-BK-C-0M', '500 GB · Czarny · Bez padów', 'zadowalajacy', 2),
  ('xbox-one', 'XO-500-BK-A-1M', '500 GB · Czarny · 1 pad', 'bardzo-dobry', 3),
  ('xbox-one', 'XO-500-BK-B-1M', '500 GB · Czarny · 1 pad', 'dobry', 4),
  ('xbox-one', 'XO-500-BK-C-1M', '500 GB · Czarny · 1 pad', 'zadowalajacy', 5),
  ('xbox-one', 'XO-500-BK-A-2M', '500 GB · Czarny · 2 pady', 'bardzo-dobry', 6),
  ('xbox-one', 'XO-500-BK-B-2M', '500 GB · Czarny · 2 pady', 'dobry', 7),
  ('xbox-one', 'XO-500-BK-C-2M', '500 GB · Czarny · 2 pady', 'zadowalajacy', 8),
  ('xbox-one', 'XO-1TB-BK-A-0M', '1 TB · Czarny · Bez padów', 'bardzo-dobry', 9),
  ('xbox-one', 'XO-1TB-BK-B-0M', '1 TB · Czarny · Bez padów', 'dobry', 10),
  ('xbox-one', 'XO-1TB-BK-C-0M', '1 TB · Czarny · Bez padów', 'zadowalajacy', 11),
  ('xbox-one', 'XO-1TB-BK-A-1M', '1 TB · Czarny · 1 pad', 'bardzo-dobry', 12),
  ('xbox-one', 'XO-1TB-BK-B-1M', '1 TB · Czarny · 1 pad', 'dobry', 13),
  ('xbox-one', 'XO-1TB-BK-C-1M', '1 TB · Czarny · 1 pad', 'zadowalajacy', 14),
  ('xbox-one', 'XO-1TB-BK-A-2M', '1 TB · Czarny · 2 pady', 'bardzo-dobry', 15),
  ('xbox-one', 'XO-1TB-BK-B-2M', '1 TB · Czarny · 2 pady', 'dobry', 16),
  ('xbox-one', 'XO-1TB-BK-C-2M', '1 TB · Czarny · 2 pady', 'zadowalajacy', 17)
) as v(model_slug, sku, option_value, grade, sort)
join shop_models m on m.slug = v.model_slug
on conflict do nothing;

commit;
